cluster:
  name: yandex
  labels: {}
  annotations: {}

cloudCredentialSecretName: ""

kubernetesVersion: v1.26.11+rke2r1

registries:
  mirrors:
    docker.io:
      endpoint:
      - https://mirror.gcr.io

yandex:
  endpoint: api.cloud.yandex.net:443
  imageFamily: ubuntu-2204-lts
  imageFolderId: standard-images
  platformId: standard-v3
  useInternalIp: true
  token: ""
  cloudId: ""
  folderId: ""
  
nodepools:
  - name: brain-a
    etcd: true
    controlplane: true
    quantity: 1
    coreFraction: 20
    cpu: 4
    memory: 6
    disk: 20
  - name: worker-a
    worker: true
    quantity: 1
    coreFraction: 20
    cpu: 2
    memory: 6
    disk: 30
    autoscale: true
    labels:
      nodepool: worker
  - name: loadbalancer-a
    worker: true
    quantity: 1
    coreFraction: 20
    cpu: 1
    memory: 1
    disk: 20
    labels:
      nodepool: loadbalancer
    taints:
      - effect: NoSchedule
        key: loadbalancer
        value: service
    nat: true

additionalManifest: |-
  apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  metadata:
    name: rke2-ingress-nginx
    namespace: kube-system
  spec:
    valuesContent: |-
      controller:
        nodeSelector: 
          nodepool: loadbalancer
        tolerations:
        - effect: NoSchedule
          key: loadbalancer
          operator: Equal
          value: service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi

machineGlobalConfig:
  cluster-domain: yandex.local
  cni: cilium

machineSelectorConfig: []

chartValues:
  rke2-cilium: # https://docs.cilium.io/en/v1.12/gettingstarted/egress-gateway/
    bpf:
      masquerade: true
    egressGateway:
      enabled: true
    kubeProxyReplacement: strict
    l7Proxy: false

upgradeStrategy:
  controlPlaneConcurrency: "1"
  controlPlaneDrainOptions:
    deleteEmptyDirData: true
    disableEviction: false
    enabled: true
    force: false
    gracePeriod: -1
    ignoreDaemonSets: true
    ignoreErrors: false
    skipWaitForDeleteTimeoutSeconds: 0
    timeout: 120
  workerConcurrency: "1"
  workerDrainOptions:
    deleteEmptyDirData: true
    disableEviction: false
    enabled: true
    force: false
    gracePeriod: -1
    ignoreDaemonSets: true
    ignoreErrors: false
    skipWaitForDeleteTimeoutSeconds: 0
    timeout: 120

etcd:
  disableSnapshots: false
  s3: null
  snapshotRetention: 12
  snapshotScheduleCron: 0 */4 * * *