{{- $clustername := .Values.cluster.name }}
{{- $hetzner := .Values.hetzner }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: HetznerConfig
metadata:
  generateName: {{ $clustername }}-{{ $nodepool.name }}
  name: {{ $clustername }}-{{ $nodepool.name }}
  namespace: fleet-default
apiToken: null
autoSpread: {{ $nodepool.autoSpread | default "false" }}
disablePublic: {{ $nodepool.disablePublic | default "false" }}
disablePublic4: {{ $nodepool.disablePublic4 | default "false" }}
disablePublic6: {{ $nodepool.disablePublic6 | default "false" }}
existingKeyId: {{ $nodepool.existingKeyId | default "null" }}
existingKeyPath: {{ $nodepool.existingKeyPath | default "null" }}
image: {{ $hetzner.image }}
imageId: {{ $nodepool.imageId | default "null" }}
placementGroup: {{ $nodepool.placementGroup | default "null" }}
primaryIpv4: {{ $nodepool.primaryIpv4 | default "null" }}
primaryIpv6: {{ $nodepool.primaryIpv6 | default "null" }}
serverLocation: {{ $nodepool.serverLocation | default "null" }}
serverType: {{ $nodepool.serverType | default "cx21" }}
sshPort: "22"
sshUser: {{ $nodepool.sshUser | default "root" }}
usePrivateNetwork: {{ $nodepool.usePrivateNetwork | default "false" }}
userData: null
userDataFromFile: {{ $hetzner.userDataFromFile }}
---
{{- end }}