{{- $clustername := .Values.cluster.name }}
{{- $cloudcredential := .Values.cloudCredentialSecretName }}
{{- $hetzner := .Values.hetzner }}
{{- range $index, $nodepool := .Values.nodepools }}
{{- if eq $nodepool.autoscale true }}
apiVersion: rke-machine.cattle.io/v1
kind: HetznerMachineTemplate
metadata:
  annotations:
    objectset.rio.cattle.io/id: rke-cluster
    objectset.rio.cattle.io/owner-gvk: provisioning.cattle.io/v1, Kind=Cluster
    objectset.rio.cattle.io/owner-name: {{ $clustername }}
    objectset.rio.cattle.io/owner-namespace: fleet-default
    rke.cattle.io/cloned-from-group-version: rke-machine-config.cattle.io/v1
    rke.cattle.io/cloned-from-kind: HetznerConfig
    rke.cattle.io/cloned-from-name: {{ $clustername }}-{{ $nodepool.name }}
  labels:
  name: {{ $clustername }}-{{ $nodepool.name }}
  namespace: fleet-default
spec:
  clusterName: {{ $clustername }}
  template:
    spec:
      common:
        cloudCredentialSecretName: {{ $cloudcredential }}
        {{- if $nodepool.labels }}
        labels:
{{ toYaml $nodepool.labels | indent 10 }}
        {{- end }}
        {{- if $nodepool.taints }}
        taints:
{{ toYaml $nodepool.taints | indent 10 }}
        {{- end }}
      apiToken: null
      autoSpread: {{ $nodepool.autoSpread | default "false" }}
      disablePublic: {{ $nodepool.disablePublic | default "false" }}
      disablePublic4: {{ $nodepool.disablePublic4 | default "false" }}
      disablePublic6: {{ $nodepool.disablePublic6 | default "false" }}
      existingKeyId: {{ $nodepool.existingKeyId | default "null" }}
      existingKeyPath: {{ $nodepool.existingKeyPath | default "null" }}
      image: {{ $hetzner.image }}
      imageId: {{ $nodepool.imageId | default "null" }}
      placementGroup: {{ $nodepool.placementGroup | default "null" }}
      primaryIpv4: {{ $nodepool.primaryIpv4 | default "null" }}
      primaryIpv6: {{ $nodepool.primaryIpv6 | default "null" }}
      serverLocation: {{ $nodepool.serverLocation | default "null" }}
      serverType: {{ $nodepool.serverType | default "cx21" }}
      sshPort: "22"
      sshUser: {{ $nodepool.sshUser | default "root" }}
      usePrivateNetwork: {{ $nodepool.usePrivateNetwork | default "false" }}
      userData: null
      userDataFromFile: {{ $hetzner.userDataFromFile }}
---
{{- end }}
{{- end }}